### ISSUE TITLE
게시판 basic, free 스킨 병합 및 미리보기 기능 제거

### ISSUE THREAD

**Issue by kkigomi** [damoang/theme#152]
## AS-IS
`free` 스킨은 "회원만 보기" 기능을 위해 분리된 것으로 보입니다.

이 두 스킨의 차이는 이 기능의 차이만 있습니다.  
들여쓰기, 줄 끝 공백, 개행 문자 등의 사소한 차이는 있으나 기능, 표현에 영향을 주지 않습니다.

## TO-BE
스킨 변경 시 두 곳을 모두 변경해줘야하는 문제가 있고, 스킨의 파일이 꽤나 다양하기 때문에 관리의 어려움이 증가할 것 같습니다.

`free` 스킨을 제거하고 `basic` 스킨에서 "회원만 보기" 설정을 추가하여 자유게시판에서만 이 기능을 활성화해 사용하면 좋을 것 같습니다.

## Tasks

- [x] "회원만 보기" 기능을 스킨 옵션으로 추가
  - 최고관리자만 이 설정을 변경 권한을 가져야 함
  - 옵션이 변경되어도 기존 "회원만 보기" 설정된 게시물은 기능을 유지
- [x] 나리야 빌더의 "미리보기(마우스 hover 시 썸네일)" 기능을 위한 목록 페이지에서 썸네일 생성 로직 제거
- [x] 현재 free 스킨은 임시 유지 후 사이트 설정 변경 후 제거하는 과정을 별도로 처리

**Comment by damoang-net** [comment]
저도 이게 좋을 것 같아요.
